version: '3'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ecolife
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    volumes:
    - ./data/db:/var/lib/mysql
    ports:
      - 3306:3306
